# Docs site settings
title: Cascade Assets
baseurl: "cascade-assets" # the subpath of your site, e.g. /blog/
exclude:
  - dist_prod
  - dist_dev
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Procfile
  - Rakefile

# Local config asset settings
assets:
  dirname: _assets
  baseurl: /_assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  js_compressor: ~
  css_compressor: none
  cachebust: hard
  cache: true
  gzip: [ text/css, application/javascript ]
  version: 1
