# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ca26aefb7a666ed857e1ee4fa9903c6adc89c57c2ce6ccafe62a65c2fe3edb698a48b3123d3792ca7aef980917e9a5965c6cebce57290c02f5caf436352d73

test:
  secret_key_base: 5c60d1186c394a0e0d0cb3f9777f6b9d4d7b74662341358cce1dfb34359605b46163c63d03744a6fd6b27e90f88eb691c4af04e2a1eebcc25f895a1877bb9b12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
